;;; Automatically generated by ‘recentf’ on Mon Apr 11 15:50:02 2022.

(setq recentf-list
      '(
        "/home/max/.emacs.d/init.el"
        "/home/max/LINK/list.cpp"
        "/home/max/LINK/main.cpp"
        "/home/max/LINK/run"
        "/home/max/LINK/list.hpp"
        "/home/max/UNI/CPP/BAUM/node.hpp"
        "/home/max/UNI/CPP/BAUM/node.cpp"
        "/home/max/UNI/CPP/main.cpp"
        "/home/max/UNI/CPP/lagerware.cpp"
        "/home/max/UNI/CPP/restposten.cpp"
        "/home/max/UNI/CPP/ware.cpp"
        "/home/max/UNI/CPP/main"
        "/home/max/UNI/CPP/ware.hpp"
        "/home/max/UNI/CPP/run.sh"
        "/home/max/UNI/CPP/restposten.hpp"
        "/home/max/UNI/CPP/lagerware.hpp"
        "/home/max/.emacs.d/valgrind-config.el"
        "/home/max/TEMP/ss.c"
        "/home/max/TEMP/size.cpp"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
