;;; Automatically generated by ‘recentf’ on Mon Mar  7 01:00:23 2022.

(setq recentf-list
      '(
        "/home/max/CPP/animal.cpp"
        "/home/max/.emacs.d/init.el"
        "/home/max/.emacs.d/company-config.el"
        "/home/max/.emacs.d/clang-format-config.el"
        "/home/max/.Xresources"
        "/home/max/CPP/newfile.cpp"
        "/home/max/CPP/ttt.cpp"
        "/home/max/CPP/type.cpp"
        "/home/max/LANGUAGE/rus.cpp"
        "/home/max/socket.cpp"
        "/home/max/newfile.cpp"
        "/home/max/string.cpp"
        "/home/max/fuck.py"
        "/home/max/fuck.lisp"
        "/home/max/CPP/test.cpp"
        "/home/max/CPP/sci.cpp"
        "/home/max/.emacs.d/elpa/xah-fly-keys-20210520.540/xah-fly-keys.el"
        "/home/max/.emacs.d/arduino.el"
        "/home/max/.emacs.d/xah-fly-keys-config.el"
        "/home/max/DREHBEWEGUNG/aufgaben.tex"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
