;;; Automatically generated by ‘recentf’ on Mon Sep 20 22:18:52 2021.

(setq recentf-list
      '(
        "/home/lord/.emacs.d/exwm-my-config.el"
        "/home/lord/.emacs.d/init.el"
        "/home/lord/.emacs.d/elpa/exwm-0.24/exwm-autoloads.el"
        "/home/lord/.emacs.d/elpa/xelb-0.18/xelb-autoloads.el"
        "/sudo:root@lord:/usr/share/xsessions/emacs.desktop"
        "/home/lord/.emacs.d/pulse-config.el"
        "/home/lord/.emacs.d/global-keys.el"
        "/home/lord/RUBY/WEB/index.html"
        "/home/lord/RUBY/WEB/test.html"
        "/home/lord/RUBY/GTK/tk.rb"
        "/home/lord/RUBY/TK/first.rb"
        "/home/lord/.emacs.d/emacs-looks.el"
        "/home/lord/.emacs.d/company-config.el"
        "/home/lord/.emacs.d/c-programming-config.el"
        "/home/lord/.emacs.d/tramp-config.el"
        "/home/lord/.emacs.d/eshell-config.el"
        "/home/lord/.emacs.d/webmode-config.el"
        "/home/lord/ip6.c"
        "/home/lord/JS/index.html"
        "/home/lord/fuck.c"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
