;;; Automatically generated by ‘recentf’ on Tue Jul 20 19:46:27 2021.

(setq recentf-list
      '(
        "/home/long/MOJO/work.c"
        "/home/long/MOJO/hello.c"
        "/usr/include/sys/user.h"
        "/home/long/MOJO/main.cpp"
        "/home/long/MOJO/value.c"
        "/home/long/MOJO/value.cpp"
        "/home/long/EP/gongo.c"
        "/home/long/.emacs.d/init.el"
        "/home/long/.Xresources"
        "/home/long/EP/linger.c"
        "/home/long/BANG/maker.c"
        "/home/long/EP/new.c"
        "/home/long/EP/log.c"
        "/home/long/vec.cpp"
        "/home/long/pollos.c"
        "/home/long/.clang-format"
        "/home/long/letme.c"
        "/home/long/.emacs.d/clang-format-config.el"
        "/home/long/EP/clean.c"
        "/home/long/EP/easy.c"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
