;;; Automatically generated by ‘recentf’ on Sun Aug  1 19:08:24 2021.

(setq recentf-list
      '(
        "/home/long/CONV/conv.s"
        "/home/long/.emacs.d/ranger-my-config.el"
        "/home/long/.emacs.d/init.el"
        "/home/long/.emacs.d/tramp"
        "/home/long/RET/new.s"
        "/home/long/MOJO/work.c"
        "/home/long/MOJO/hello.c"
        "/usr/include/sys/user.h"
        "/home/long/MOJO/main.cpp"
        "/home/long/MOJO/value.c"
        "/home/long/MOJO/value.cpp"
        "/home/long/EP/gongo.c"
        "/home/long/.Xresources"
        "/home/long/EP/linger.c"
        "/home/long/BANG/maker.c"
        "/home/long/EP/new.c"
        "/home/long/EP/log.c"
        "/home/long/vec.cpp"
        "/home/long/pollos.c"
        "/home/long/.clang-format"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
