;;; Automatically generated by ‘recentf’ on Fri Aug 20 17:12:01 2021.

(setq recentf-list
      '(
        "/home/lord/.Xresources"
        "/home/lord/hello.cpp"
        "/home/lord/UTS/malo.c"
        "/home/lord/UTS/mucho.c"
        "/home/lord/IND/serv.c"
        "/home/lord/IND/fine.c"
        "/home/lord/IND/rec.pl"
        "/home/lord/IND/ind.c"
        "/home/lord/mlt/net.cpp"
        "/home/lord/.clang-format"
        "/usr/include/sys/user.h"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
