;;; Automatically generated by ‘recentf’ on Sat Jun 12 17:47:53 2021.

(setq recentf-list
      '(
        "/home/long/KING/con.c"
        "/home/long/KING/inc.c"
        "/home/long/KING/tt.c"
        "/home/long/.emacs.d/init.el"
        "/home/long/KING/aton.c"
        "/home/long/.emacs.d/helm-my-config.el"
        "/home/long/.emacs.d/xah-fly-keys-config.el"
        "/home/long/MA/SOME/welcome.el"
        "/home/long/MA/welcome.el"
        "/home/long/MA/SOME/cool.pl"
        "/home/long/.emacs.d/backup-config.el"
        "/home/long/.emacs.d/elisp-config.el"
        "/home/long/.emacs.d/gtags-config.el"
        "/home/long/KING/find.c"
        "/home/long/.emacs.d/elpa/helm-ag-20210305.334/helm-ag-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
