;;; Automatically generated by ‘recentf’ on Thu Jun 10 01:55:01 2021.

(setq recentf-list
      '(
        "/home/long/MA/SOME/welcome.el"
        "/home/long/MA/welcome.el"
        "/home/long/MA/SOME/cool.pl"
        "/home/long/.emacs.d/init.el"
        "/home/long/.emacs.d/backup-config.el"
        "/home/long/.emacs.d/elisp-config.el"
        "/home/long/.emacs.d/helm-my-config.el"
        "/home/long/.emacs.d/gtags-config.el"
        "/home/long/KING/find.c"
        "/home/long/.emacs.d/elpa/helm-ag-20210305.334/helm-ag-autoloads.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
