;;; Automatically generated by ‘recentf’ on Thu Mar 24 21:27:31 2022.

(setq recentf-list
      '(
        "/home/grande/buffer_list.lol"
        "/home/grande/ERR/max_rad.cpp"
        "/home/grande/ERR/shape.cpp"
        "/home/grande/ERR/vir.cpp"
        "/home/grande/ERR/fuck.cpp"
        "/home/grande/.emacs.d/init.el"
        "/home/grande/LGAME/creature.hpp"
        "/home/grande/pure.cpp"
        "/home/grande/PYTHON/all.py"
        "/home/grande/ERR/integer_error.hpp"
        "/home/grande/.emacs.d/workgroups-config.el"
        "/home/grande/.emacs.d/elpa/workgroups-20110726.1641/workgroups-autoloads.el"
        "/home/grande/.emacs.d/elpa/use-package-20210207.1926/use-package-autoloads.el"
        "/home/grande/.emacs.d/elpa/bind-key-20210210.1609/bind-key-autoloads.el"
        "/home/grande/LGAME/fruit.cpp"
        "/home/grande/.emacs.d/elpa/gruvbox-theme-20220101.1208/gruvbox-theme-autoloads.el"
        "/home/grande/LGAME/main.cpp"
        "/home/grande/LGAME/monster.hpp"
        "/home/grande/LGAME/player.hpp"
        "/home/grande/LGAME/player.cpp"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
